[tryton] CI

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,356 +1,170 @@
-workflow:
-  rules:
-    - if: $CI_COMMIT_BRANCH =~ /^topic\/.*/ && $CI_PIPELINE_SOURCE == "push"
-      when: never
-    - when: always
-
 stages:
-  - preparation
-  - check
-  - test
+  - synchronize
+  - create
   - build
+  - destroy
 
-packages:
-  stage: preparation
-  rules:
-    - when: always
-  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/tryton/ci
-  variables:
-    DOC_BASE_URL: ${CI_PROJECT_DIR}/docs
-  script:
-    - .gitlab-scripts/generate-packages.sh packages
-  artifacts:
-    paths:
-      - packages/
-    expire_in: 1 week
+################## extends ##################
 
-documentation:
-  stage: preparation
-  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/sphinxdoc/sphinx
-  script:
-    - .gitlab-scripts/generate-doc.sh docs
-  artifacts:
-    paths:
-      - docs/
-    expire_in: 1 week
-  rules:
-    - changes:
-        - "**/*/doc/**/*"
-        - "**/*/tryton.cfg"
-        - "**/*/CHANGELOG"
-        - "readthedocs/**/*"
-
-.check:
-  stage: check
-  needs: []
-  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/tryton/ci
-
-.check-doc:
-  extends: .check
-  needs:
-    - documentation
-  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/sphinxdoc/sphinx
-  variables:
-    DOC_BASE_URL: ${CI_PROJECT_DIR}/docs
-    DOC_DIR: doc
-  cache:
-    paths:
-      - .cache/pip/http
+.terraform:
   before_script:
-    - pip install sphinx-lint rstcheck[sphinx]
+    - apt update && apt install -y --no-install-recommends --no-install-suggests git gnupg software-properties-common curl openssh-client gettext
+    - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
+    - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
+    - apt update && apt install -y --no-install-recommends --no-install-suggests terraform
+    - cd "${CI_PROJECT_DIR}/.gitlab/terraform"
+    - |-
+      terraform init \
+        -backend-config="address=${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${CI_COMMIT_REF_SLUG}_${CI_PIPELINE_ID}" \
+        -backend-config="lock_address=${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${CI_COMMIT_REF_SLUG}_${CI_PIPELINE_ID}/lock" \
+        -backend-config="unlock_address=${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${CI_COMMIT_REF_SLUG}_${CI_PIPELINE_ID}/lock" \
+        -backend-config="username=project_${CI_PROJECT_ID}_bot" \
+        -backend-config="password=${PROJECT_API_TOKEN}" \
+        -backend-config="lock_method=POST" \
+        -backend-config="unlock_method=DELETE" \
+        -backend-config="retry_wait_min=5"
+    - envsubst < "terraform.tfvars.template" > "terraform.tfvars"
+
+################## Includes ##################
+
+include:
+  - project: 'coopengo/devops/gitlab-ci-template'
+    ref: master
+    file: '/Jobs/reference.debian.gitlab-ci.yml'
+
+################## Jobs ##################
+
+synchronize:pipeline:
+  stage: synchronize
+  image: bitnami/git:latest
+  before_script:
+    - mkdir -p ~/.ssh
+    - chmod 700 ~/.ssh
+    - ssh-keyscan -H "${CI_SERVER_HOST}" >>~/.ssh/known_hosts
+    - cat "${SSH_KEY}" > ~/.ssh/id_rsa
+    - chmod 400 ~/.ssh/id_rsa
+    - git config --global user.email "${GITLAB_USER_EMAIL}"
+    - git config --global user.name "🤖 GitLab CI/CD 🤖"
+    - git remote set-url origin git@${CI_SERVER_HOST}:${CI_PROJECT_PATH}.git
+    - git fetch --all
   script:
-    - cd "${PACKAGE}"
-    - python -m sphinx -T -E -W -n -b html ${DOC_DIR} _build/html
-    - python -m sphinxlint ${DOC_DIR}
-    - rstcheck --recursive ${DOC_DIR}
-    - |
-      if [ "${CHECK_LINK}" ]; then
-      python -m sphinx -T -E -W -n -b linkcheck ${DOC_DIR} _build;
+    - |-
+      for BRANCH in $(git ls-remote --refs -h origin -l "coog-*" | cut -s -d '/' -f3 | grep -E "^(coog-[[:digit:]]{1,2}).([[:digit:]]{1,2})$" )
+      do
+        git checkout "${BRANCH}"
+        git checkout "${CI_COMMIT_SHORT_SHA}" .gitlab-ci.yml sign-client.bat .gitlab/
+        git commit -m "Merge .gitlab-ci.yml, sign-client.bat and build directory from \"${CI_COMMIT_SHORT_SHA}\"" || echo "Nothing to do"
+      done
+      git push --all
+  rules:
+    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
+      changes:
+        - ".gitlab-ci.yml"
+        - ".gitlab/**/*"
+        - "sign-client.bat"
+
+create:windows:
+  stage: create
+  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
+  before_script:
+    - apt update && apt install -y --no-install-recommends git
+    - |-
+      if [[ $(git tag --points-at HEAD | wc -l) -ne 1 && ${CI_PIPELINE_SOURCE} != "web" ]]
+      then
+        echo "Last commit doesn't have 1 tag, that mean there is no change"
+        echo "Pipeline stop here"
+        exit 1
       fi
-  rules:
-    - if: $CI_COMMIT_TAG == null
-      changes:
-        - ${PACKAGE}/${DOC_DIR}/**/*
-        - ${PACKAGE}/tryton.cfg
-        - ${PACKAGE}/CHANGELOG
-      when: on_success
-    - when: never
-
-.check-doc-readme:
-  extends: .check-doc
+    - !reference [.terraform, before_script]
   script:
-    - python -m sphinxlint README.rst
-    - rstcheck README.rst
-  rules:
-    - if: $CI_COMMIT_TAG == null
-      changes:
-        - README.rst
-      when: on_success
-    - when: never
-
-check-doc-readthedocs:
-  extends: .check-doc
-  variables:
-    PACKAGE: readthedocs
-    DOC_DIR: .
-  rules:
-    - if: $CI_COMMIT_TAG == null
-      changes:
-        - ${PACKAGE}/**/*
-      when: on_success
-    - when: never
-
-.check-code:
-  extends: .check
-  rules:
-    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
-      when: always
-
-check-flake8:
-  extends: .check-code
-  script:
-    - flake8 --exclude 'cookiecutter*'
-
-check-isort:
-  extends: .check-code
-  script:
-    - isort --multi-line VERTICAL_GRID --check --diff --skip-glob 'cookiecutter*' .
-
-check-dist:
-  stage: check
-  needs:
-    - packages
-  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/tryton/ci
-  script:
-    - twine check packages/*
-
-check-ci-modules:
-  extends: .check
-  script:
-    - python .gitlab-scripts/generate-ci.py $TMPDIR/gitab-ci-modules.yml
-    - cmp .gitlab-ci-modules.yml $TMPDIR/gitab-ci-modules.yml
-
-check-cookiecutter-module:
-  extends: .check
-  cache:
-    paths:
-      - .cache/pip/http
-  before_script:
-    - pip install cookiecutter
-  script:
-    - cookiecutter --no-input cookiecutter-module -o /tmp
-    - flake8 /tmp/my_module
-    - isort --multi-line VERTICAL_GRID --check --diff /tmp/my_module
-  rules:
-    - changes:
-        - cookiecutter-module/**/*
-
-.test:
-  stage: test
-  rules:
-    - if: $CI_COMMIT_TAG == null
-      changes:
-        - ${PACKAGE}/**/*
-      when: on_success
-    - if: '$CI_COMMIT_TAG =~ $TAG_PATTERN'
-      when: on_success
-    - when: never
-
-.test-tox:
-  extends: .test
-  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:${PYTHON_VERSION}
-  variables:
-    PIP_FIND_LINKS: file://${CI_PROJECT_DIR}/packages/
-    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
-  cache:
-    paths:
-      - .cache/pip/http
-  before_script:
-    - pip install tox
-  script:
-    - tox -e "py${PYTHON_VERSION/./}" -c "${PACKAGE}" -vv -- -v --output-file junit.xml
-  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
+    - terraform plan
+    - terraform apply --auto-approve
+    - cd "${CI_PROJECT_DIR}"
+    - |-
+      export EC2_STATE_TRY="1"
+      while [[ $(aws ec2 describe-instances --filters "Name = instance.group-name, Values = tryton-${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}" --query 'Reservations[*].Instances[0].State.Name' --output text) != "running" ]] &&
+            [[ "$EC2_STATE_TRY" -le "10" ]]
+      do
+        echo "Warning : Must wait 60 second minimum else ssh refuse connection"
+        echo "Instance not ready... Retry in 60 sec - ${EC2_STATE_TRY}"
+        sleep 60
+        let ++EC2_STATE_TRY
+      done
+      if [[ "$EC2_STATE_TRY" -ge "10" ]]
+      then
+        echo "Instance still not running"
+        exit 1
+      fi
+    - |-
+      export INSTANCE_IP_TRY="1"
+      while [[ "${INSTANCE_IP}" == "" ]] && [[ "${INSTANCE_IP_TRY}" -le "20" ]]
+      do
+        export INSTANCE_IP=$(aws ec2 describe-instances --filters "Name = instance.group-name, Values = tryton-${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}" --query 'Reservations[*].Instances[0].PrivateIpAddress' --output text)
+        if [[ "${INSTANCE_IP}" == "" ]]
+        then
+          echo "INSTANCE_IP variable is empty."
+          echo "Wait 10 seconds before retry"
+          echo "Try ${INSTANCE_IP_TRY}/20"
+          sleep 10
+          (( ++INSTANCE_IP_TRY ))
+        fi
+      done
+      if [[ "$INSTANCE_IP" == "" ]]
+      then
+        echo "Couldn't get INSTANCE_IP"
+        exit 1
+      fi
+    - envsubst < "${CI_PROJECT_DIR}/.gitlab/env/tryton.env" > tryton.env
   artifacts:
-    reports:
-      junit: ${PACKAGE}/junit.xml
-      coverage_report:
-        coverage_format: cobertura
-        path: ${PACKAGE}/coverage.xml
-  parallel:
-    matrix:
-      - PYTHON_VERSION: ["3.8", "3.9", "3.10", "3.11"]
-
-.test-db:
-  extends: .test-tox
-  variables:
-    DB_CACHE: /tmp/cache
-  script:
-    - tox -e "py${PYTHON_VERSION/./}-${DATABASE}" -c "${PACKAGE}" -vv -- -v --output-file junit.xml
-
-.test-sqlite:
-  extends: .test-db
-  variables:
-    DATABASE: sqlite
-
-.test-postgresql:
-  extends: .test-db
-  variables:
-    DATABASE: postgresql
-    POSTGRESQL_URI: postgresql://postgres@postgresql:5432/
-    POSTGRES_HOST_AUTH_METHOD: trust
-  services:
-    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/postgres
-      alias: postgresql
-      command: ["-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
-
-.test-postgis:
-  extends: .test-db
-  variables:
-    DATABASE: postgis
-    POSTGIS_URI: postgis://postgres@postgis:5432/
-    POSTGRES_HOST_AUTH_METHOD: trust
-  script:
-    - tox -e "py${PYTHON_VERSION/./}" -c "${PACKAGE}" -vv -- -v --output-file junit.xml
-  services:
-    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/postgis/postgis
-      alias: postgis
-      command: ["-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
-
-.test-npm:
-  extends: .test
-  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node
-  variables:
-    NODE_CACHE_DIR: "$CI_PROJECT_DIR/.cache/npm"
-  cache:
     paths:
-      - .cache/npm
-  before_script:
-    - sh .gitlab-scripts/bower_allow_root.sh
-  script:
-    - cd "${PACKAGE}"
-    - npm -s install --cache ${NODE_CACHE_DIR} --unsafe-perm --legacy-peer-deps
-    - npm test
-  artifacts:
-    reports:
-      junit: ${PACKAGE}/_build/test-reports/*.xml
+      - tryton.env
+    expire_in: 2 hours
+  rules:
+    - if: $CI_COMMIT_TAG =~ /^coog-(([[:digit:]]{1,2}).([[:digit:]]{1,2}))/
 
-.trigger-doc-build:
+build:tryton_client:
   stage: build
-  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/tryton/ci
-  script:
-    - .gitlab-scripts/trigger-readthedocs.py -c "${RTD_CONFIG}" -p "${PACKAGE}" -b "${CI_COMMIT_BRANCH#branch/}"
-  rules:
-    - if: $CI_COMMIT_BRANCH =~ /^branch\/.*/
-      changes:
-        - ${PACKAGE}/doc/**/*
-        - ${PACKAGE}/tryton.cfg
-        - ${PACKAGE}/CHANGELOG
-      allow_failure: true
-
-trigger-doc-build-readthedocs:
-  extends: .trigger-doc-build
+  image: darkwizard242/ansible:debian-bullseye
   variables:
-    PACKAGE: readthedocs
-  rules:
-    - if: $CI_COMMIT_BRANCH =~ /^branch\/.*/
-      changes:
-        - ${PACKAGE}/**/*
-      allow_failure: true
-
-check-doc-trytond:
-  extends: .check-doc
-  variables:
-    PACKAGE: trytond
-
-check-trytond-rng:
-  extends: .check
-  cache:
-    paths:
-      - .cache/pip/http
+    ANSIBLE_FORCE_COLOR: "true"
   before_script:
-    - pip install rnc2rng
+    - ansible --version
+    - apt update && apt install --no-install-recommends --no-install-suggests -y git sudo openssh-client nmap
+    - source tryton.env
+    - !reference [.git_with_ssh:debian, before_script]
   script:
-    - python trytond/setup.py update_rng
-    - |
-      if [ `hg status trytond| wc -l` -ne 0 ]; then
-        false
-      fi
+    - |-
+      export SSH_CONNECTION="1"
+      while [[ "$(nmap ${INSTANCE_IP} -Pn -p 22 | egrep -io 'open|closed|filtered')" != "open" ]] && [[ "${SSH_CONNECTION}" -le "20" ]]
+      do
+        echo "Windows server (${INSTANCE_IP}) is not available."
+        echo "Retry in 60 seconds"
+        echo "Try ${SSH_CONNECTION}/20"
+        sleep 60
+        (( ++SSH_CONNECTION ))
+      done
+    - ssh -T -o "StrictHostKeyChecking=no" administrator@"${INSTANCE_IP}" \
+        "PATH=\"${PATH}:/c/msys32/mingw32/bin\" && cd tryton && /usr/bin/git fetch --tags --all -p -f && /usr/bin/git reset --hard origin/master && /usr/bin/git clean -fd && /usr/bin/git checkout ${CI_COMMIT_REF_NAME} && source .gitlab/env/windows.env && ./win-make.sh build ${COOPENGO_SOFTWARE_CERT_PASSWORD} ${WINDOWS_USER_PASSWORD} && ./win-make.sh upload ${GITHUB_TOKEN}"
+  needs:
+    - create:windows
   rules:
-    - changes:
-        - trytond/**/*.rnc
-        - trytond/**/*.rng
+    - if: $CI_COMMIT_TAG =~ /^coog-(([[:digit:]]{1,2}).([[:digit:]]{1,2}))/
+    
 
-trigger-doc-build-trytond:
-  extends: .trigger-doc-build
-  variables:
-    PACKAGE: trytond
-
-test-trytond-sqlite:
-  extends: .test-sqlite
-  variables:
-    PACKAGE: trytond
-    TAG_PATTERN: '/^trytond-.*/'
-
-test-trytond-postgresql:
-  extends: .test-postgresql
-  variables:
-    PACKAGE: trytond
-    TAG_PATTERN: '/^trytond-.*/'
-
-check-doc-trytond-gis:
-  extends: .check-doc
-  variables:
-    PACKAGE: trytond-gis
-
-trigger-doc-build-trytond-gis:
-  extends: .trigger-doc-build
-  variables:
-    PACKAGE: trytond-gis
-
-test-trytond-gis-postgis:
-  extends: .test-postgis
-  variables:
-    PACKAGE: trytond-gis
-    TAG_PATTERN: '/^trytond-gis-.*/'
-
-check-doc-proteus:
-  extends: .check-doc
-  variables:
-    PACKAGE: proteus
-
-trigger-doc-build-proteus:
-  extends: .trigger-doc-build
-  variables:
-    PACKAGE: proteus
-
-test-proteus:
-  extends: .test-tox
-  variables:
-    PACKAGE: proteus
-    TAG_PATTERN: '/^proteus-.*/'
-
-check-doc-tryton:
-  extends: .check-doc
-  variables:
-    PACKAGE: tryton
-
-trigger-doc-build-tryton:
-  extends: .trigger-doc-build
-  variables:
-    PACKAGE: tryton
-
-test-tryton:
-  extends: .test-tox
-  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/tryton/tryton-test:${PYTHON_VERSION}
-  variables:
-    PACKAGE: tryton
-    TAG_PATTERN: '/^tryton-.*/'
-
-test-sao:
-  extends: .test-npm
-  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/tryton/sao-test
-  variables:
-    PACKAGE: sao
-    TAG_PATTERN: '/^sao-.*/'
-
-include: '.gitlab-ci-modules.yml'
+destroy:windows:
+  stage: destroy
+  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
+  before_script:
+    - !reference [.terraform, before_script]
+  script:
+    - terraform plan --refresh-only
+    - terraform destroy --auto-approve
+    - curl -s --header "Private-Token:${PROJECT_API_TOKEN}" --request DELETE "${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${CI_COMMIT_REF_SLUG}_${CI_PIPELINE_ID}"
+  needs:
+    - job: build:tryton_client
+      artifacts: false
+    - job: create:windows
+      artifacts: false
+  rules:
+    - if: $CI_COMMIT_TAG =~ /^coog-(([[:digit:]]{1,2}).([[:digit:]]{1,2}))/
+      when: always
